print error message from curl/wget before the summary

diff --git a/install b/install
--- a/install
+++ b/install
@@ -208,14 +208,14 @@ END
     local archive="$cache_dir"/"$file".tmp.$$.tar.gz
     if command -v curl >/dev/null 2>&1; then
       if ! err="$(command curl -fsSLo "$archive" -- "$url" 2>&1)"; then
-        >&2 echo "[gitstatus] error: failed to download gitstatusd: $url"
         >&2 printf "%s\n" "$err"
+        >&2 echo "[gitstatus] error: failed to download gitstatusd: $url"
         return 1
       fi
     elif command -v wget >/dev/null 2>&1; then
       if ! err="$(command wget -O "$archive" -- "$url" 2>&1)"; then
-        >&2 echo "[gitstatus] error: failed to download gitstatusd: $url"
         >&2 printf "%s\n" "$err"
+        >&2 echo "[gitstatus] error: failed to download gitstatusd: $url"
         return 1
       fi
     else
