show progress when downloading gitstatusd

diff --git a/install b/install
--- a/install
+++ b/install
@@ -12,14 +12,14 @@ _gitstatus_install_main() {
   local argv1=$1
   shift
 
-  local no_check= no_install= uname_s= uname_m= gitstatus_dir=
+  local no_check= no_install= uname_s= uname_m= gitstatus_dir= dl_status=
   local opt= OPTARG= OPTIND=1
 
-  while getopts ':s:m:d:fnh' opt "$@"; do
+  while getopts ':s:m:d:p:fnh' opt "$@"; do
     case "$opt" in
       h)
         command cat <<\END
-Usage: install [-s KERNEL] [-m ARCH] [-d DIR] [-f|-n] [-- CMD [ARG]...]
+Usage: install [-s KERNEL] [-m ARCH] [-d DIR] [-p CMD] [-f|-n] [-- CMD [ARG]...]
 
 If positional arguments are specified, call this on success:
 
@@ -35,6 +35,7 @@ Options:
   -s KERNEL  use this instead of lowercase `uname -s`
   -m ARCH    use this instead of lowercase `uname -m`
   -d DIR     use this instead of `dirname "$0"`
+  -p CMD     eval this every second while downloading gitstatusd
   -f         download gitstatusd even if there is one locally
   -n         do not download gitstatusd (fail instead)
 END
@@ -64,6 +65,17 @@ END
           return 1
         fi
         gitstatus_dir="$OPTARG"
+      ;;
+      p)
+        if [ -n "$dl_status" ]; then
+          >&2 echo "[gitstatus] error: duplicate option: -$opt"
+          return 1
+        fi
+        if [ -z "$OPTARG" ]; then
+          >&2 echo "[error] incorrect value of -$opt: $OPTARG"
+          return 1
+        fi
+        dl_status="$OPTARG"
       ;;
       m)
         if [ -n "$uname_m" ]; then
@@ -237,6 +249,9 @@ END
       fetch() {
         local trapped=
         trap 'trapped=1' $sig
+        if [ "$1" != 1 ] && command -v sleep >/dev/null 2>/dev/null; then
+          sleep "$1"
+        fi
         $fetch "$tmp"."$1".tar.gz -- "$2" 2>/dev/null &
         local pid=$!
         local die="trap - $sig; kill -- $pid 2>/dev/null; cleanup $1; exit 1"
@@ -262,6 +277,7 @@ END
 
       local n=
       while true; do
+        [ -z "$dl_status" ] || eval "$dl_status" || eval "$die"
         if command -v sleep >/dev/null 2>/dev/null; then
           command sleep 1
         elif command -v true >/dev/null 2>/dev/null; then
