propagate error messages from install to gitstatus_start; add a special diagnostic for rosetta2

diff --git a/install b/install
--- a/install
+++ b/install
@@ -12,14 +12,14 @@ _gitstatus_install_main() {
   local argv1="$1"
   shift
 
-  local no_check= no_install= uname_s= uname_m= gitstatus_dir= dl_status=
+  local no_check= no_install= uname_s= uname_m= gitstatus_dir= dl_status= e=
   local opt= OPTARG= OPTIND=1
 
-  while getopts ':s:m:d:p:fnh' opt "$@"; do
+  while getopts ':s:m:d:p:e:fnh' opt "$@"; do
     case "$opt" in
       h)
         command cat <<\END
-Usage: install [-s KERNEL] [-m ARCH] [-d DIR] [-p CMD] [-f|-n] [-- CMD [ARG]...]
+Usage: install [-s KERNEL] [-m ARCH] [-d DIR] [-p CMD] [-e ERRFD] [-f|-n] [-- CMD [ARG]...]
 
 If positional arguments are specified, call this on success:
 
@@ -36,6 +36,7 @@ Options:
   -m ARCH    use this instead of lowercase `uname -m`
   -d DIR     use this instead of `dirname "$0"`
   -p CMD     eval this every second while downloading gitstatusd
+  -e ERRFD   write error messages to this file descriptor
   -f         download gitstatusd even if there is one locally
   -n         do not download gitstatusd (fail instead)
 END
@@ -77,6 +78,17 @@ END
         fi
         dl_status="$OPTARG"
       ;;
+      e)
+        if [ -n "$e" ]; then
+          >&2 echo "[gitstatus] error: duplicate option: -$opt"
+          return 1
+        fi
+        if [ -z "$OPTARG" ]; then
+          >&2 echo "[error] incorrect value of -$opt: $OPTARG"
+          return 1
+        fi
+        e="$OPTARG"
+      ;;
       m)
         if [ -n "$uname_m" ]; then
           >&2 echo "[gitstatus] error: duplicate option: -$opt"
@@ -107,6 +119,7 @@ END
 
   shift "$((OPTIND - 1))"
 
+  : "${e:=2}"
   : "${gitstatus_dir:=$argv1}"
 
   if [ -n "$no_check" -a -n "$no_install" ]; then
@@ -115,12 +128,12 @@ END
   fi
 
   if [ -z "$uname_s" ]; then
-    uname_s="$(command uname -s)" || return
-    uname_s="$(printf '%s' "$uname_s" | command tr '[A-Z]' '[a-z]')" || return
+    uname_s="$(command uname -s 2>&"$e")" || return
+    uname_s="$(printf '%s' "$uname_s" | command tr '[A-Z]' '[a-z]' 2>&"$e")" || return
   fi
   if [ -z "$uname_m" ]; then
-    uname_m="$(command uname -m)" || return
-    uname_m="$(printf '%s' "$uname_m" | command tr '[A-Z]' '[a-z]')" || return
+    uname_m="$(command uname -m 2>&"$e")" || return
+    uname_m="$(printf '%s' "$uname_m" | command tr '[A-Z]' '[a-z]' 2>&"$e")" || return
   fi
 
   local daemon="${GITSTATUS_DAEMON:-}"
@@ -128,7 +141,7 @@ END
 
   if [ -z "$no_check" ]; then
     if [ -n "${daemon##/*}" ]; then
-      >&2 echo "[gitstatus] error: GITSTATUS_DAEMON is not absolute path: $daemon"
+      >&"$e" echo "[gitstatus] error: GITSTATUS_DAEMON is not absolute path: $daemon"
       return 1
     fi
     if [ -z "$daemon" -a -e "$gitstatus_dir"/usrbin/gitstatusd ]; then
@@ -137,11 +150,11 @@ END
     if [ -n "$daemon" ]; then
       local gitstatus_version= libgit2_version=
       if ! . "$gitstatus_dir"/build.info; then
-        >&2 echo "[gitstatus] internal error: failed to source build.info"
+        >&"$e" echo "[gitstatus] internal error: failed to source build.info"
         return 1
       fi
       if [ -z "$gitstatus_version" ]; then
-        >&2 echo "[gitstatus] internal error: empty gitstatus_version in build.info"
+        >&"$e" echo "[gitstatus] internal error: empty gitstatus_version in build.info"
         return 1
       fi
       [ $# = 0 ] || "$@" "$daemon" "$gitstatus_version" 0
@@ -154,14 +167,14 @@ END
     [ -n "$line" ] || continue
 
     local uname_s_glob= uname_m_glob= file= version= sha256=
-    eval "$line" || return
+    eval "$line" 2>&"$e" || return
 
     if [ -z "$uname_s_glob" -o \
          -z "$uname_m_glob" -o \
          -z "$file"         -o \
          -z "$version"      -o \
          -z "$sha256" ]; then
-      >&2 echo "[gitstatus] internal error: invalid install.info line: $line"
+      >&"$e" echo "[gitstatus] internal error: invalid install.info line: $line"
       return 1
     fi
 
@@ -192,27 +205,27 @@ END
     # No suitable gitstatusd exists. Need to download.
 
     if [ -n "$no_install" ]; then
-      >&2 echo "[gitstatus] error: no gitstatusd found and installation is disabled"
+      >&"$e" echo "[gitstatus] error: no gitstatusd found and installation is disabled"
       return 1
     fi
 
     local daemon="$cache_dir"/"$file"
 
     if [ -n "${cache_dir##/*}" ]; then
-      >&2 echo "[gitstatus] error: GITSTATUS_CACHE_DIR is not absolute: $cache_dir"
+      >&"$e" echo "[gitstatus] error: GITSTATUS_CACHE_DIR is not absolute: $cache_dir"
       return 1
     fi
-    [ -d "$cache_dir" ] || mkdir -p -- "$cache_dir" || return
+    [ -d "$cache_dir" ] || mkdir -p -- "$cache_dir" 2>&"$e" || return
 
     local tmpdir
     if ! command -v mktemp >/dev/null 2>&1 ||
         ! tmpdir="$(command mktemp -d "${TMPDIR:-/tmp}"/gitstatus-install.XXXXXXXXXX)"; then
       tmpdir="${TMPDIR:-/tmp}/gitstatus-install.tmp.$$"
-      mkdir -p -- "$tmpdir" || return
+      mkdir -p -- "$tmpdir" 2>&"$e" || return
     fi
 
     if ! command -v curl >/dev/null 2>&1 && ! command -v wget >/dev/null 2>&1; then
-      >&2 echo "[gitstatus] error: please install curl or wget"
+      >&"$e" echo "[gitstatus] error: please install curl or wget"
       return 1
     fi
 
@@ -363,14 +376,14 @@ END
       trap - $sig
 
       if [ -z "$n" ]; then
-        >&2 echo "[gitstatus] error: failed to download gitstatusd from any mirror"
-        >&2 echo ""
-        >&2 echo "  1. $url1"
-        >&2 echo "  2. $url2"
+        >&"$e" echo "[gitstatus] error: failed to download gitstatusd from any mirror"
+        >&"$e" echo ""
+        >&"$e" echo "  1. $url1"
+        >&"$e" echo "  2. $url2"
         exit 1
       fi
 
-      command tar -C "$tmpdir" -xzf "$tmpdir"/"$n".tar.gz || exit
+      command tar -C "$tmpdir" -xzf "$tmpdir"/"$n".tar.gz 2>&"$e" || exit
 
       local tmpfile
       if ! command -v mktemp >/dev/null 2>&1 ||
@@ -378,10 +391,10 @@ END
         tmpfile="$cache_dir"/gitstatusd.tmp.$$
       fi
 
-      command mv -f -- "$tmpdir"/gitstatusd-* "$tmpfile" || exit
+      command mv -f -- "$tmpdir"/gitstatusd-* "$tmpfile" 2>&"$e" || exit
       command mv -f -- "$tmpfile" "$cache_dir"/"$file" && exit
       command rm -f -- "$cache_dir"/"$file"
-      command mv -f -- "$tmpfile" "$cache_dir"/"$file" && exit
+      command mv -f -- "$tmpfile" "$cache_dir"/"$file" 2>&"$e" && exit
       command rm -f -- "$tmpfile"
       exit 1
     )
@@ -394,9 +407,9 @@ END
     return
   done <"$gitstatus_dir"/install.info
 
-  >&2 echo "[gitstatus] error: no gitstatusd found for $uname_s $uname_m"
-  >&2 echo ""
-  >&2 echo "See: https://github.com/romkatv/gitstatus/blob/master/README.md#compiling"
+  >&"$e" echo "[gitstatus] error: no gitstatusd found for $uname_s $uname_m"
+  >&"$e" echo ""
+  >&"$e" echo "See: https://github.com/romkatv/gitstatus#compiling"
   return 1
 }
 
